<a href="https://colab.research.google.com/github/kwmir113/Data-Science-Academy/blob/main/Copy_of_Clustering_ZillowDataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
https://colab.research.google.com/#create=true

In [ ]:
https://docs.google.com/document/d/10qJ863EK5yrwCCpDJ2LdffQV-7fD6OSHEapCSGWsHyI/edit?usp=sharing

In [ ]:
# Code snippet 1
# Importing the dataset
import pandas as pd
data = pd.read_csv('https://raw.githubusercontent.com/nvamsimohan/DallasDSA/refs/heads/main/Zillow%20Tarrant%20County%20Raw%20Data.csv')

data

,beds,baths,sqft,Age,lot_size,property_type,exterior_walls,roof,basement,restaurants,...,beauty_spas,active_life,median_age,married,college_grad,property_tax,insurance,median_school,num_schools,Sales_price
0,1,1,584,9,0,Apartment / Condo / Townhouse,Wood Siding,NaN,0,107,...,47,58,33,65,84,234,81,9.0,3,295850
1,1,1,612,57,0,Apartment / Condo / Townhouse,Brick,Composition Shingle,1,105,...,26,14,39,73,69,169,51,3.0,3,216500
2,1,1,615,59,0,Apartment / Condo / Townhouse,Wood Siding,NaN,0,183,...,74,62,28,15,86,216,74,8.0,3,279900
3,1,1,618,22,33541,Apartment / Condo / Townhouse,Wood Siding,NaN,0,198,...,72,83,36,25,91,265,92,9.0,3,379900
4,1,1,634,30,0,Apartment / Condo / Townhouse,Brick,NaN,0,149,...,50,73,37,20,75,88,30,9.0,3,340000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,5,6,6381,18,224334,Single-Family,Stucco,Composition Shingle,1,0,...,0,1,46,76,87,1250,381,10.0,3,385000
1879,5,6,6501,66,23086,Single-Family,Brick,Composition Shingle,1,45,...,61,11,42,73,61,1553,473,9.0,3,690000
1880,5,6,7064,27,217800,Single-Family,Metal,Composition Shingle,1,5,...,1,2,43,87,66,942,287,8.0,1,600000
1881,5,6,7500,16,8886,Single-Family,Siding (Alum/Vinyl),Asphalt,1,18,...,8,6,43,61,51,803,245,5.0,2,759900
1882,5,6,7515,64,10497,Single-Family,Brick,Composition Shingle,1,0,...,0,5,37,80,86,1459,444,9.0,3,735000

In [ ]:
# Code snippet 2
# Displaying the dataset columns
data.columns

Index(['beds', 'baths', 'sqft', 'Age', 'lot_size', 'property_type',
       'exterior_walls', 'roof', 'basement', 'restaurants', 'groceries',
       'nightlife', 'cafes', 'shopping', 'arts_entertainment', 'beauty_spas',
       'active_life', 'median_age', 'married', 'college_grad', 'property_tax',
       'insurance', 'median_school', 'num_schools', 'Sales_price'],
      dtype='object')

In [ ]:
# Code snippet 3
# Listing all the categorical columns
cat_cols = ['property_type', 'exterior_walls', 'roof']

# Creating dummy columns/hot encoding for the categorical columns
encoded_data = pd.get_dummies(data, columns=cat_cols, drop_first = True, dtype = int)

# Display the encoded_data
encoded_data

,beds,baths,sqft,Age,lot_size,basement,restaurants,groceries,nightlife,cafes,...,roof_Metal,roof_Other,roof_Roll Composition,roof_Shake Shingle,roof_Slate,roof_Wood Shake/ Shingles,roof_asphalt,"roof_asphalt,shake-shingle",roof_composition,roof_shake-shingle
0,1,1,584,9,0,0,107,9,30,19,...,0,0,0,0,0,0,0,0,0,0
1,1,1,612,57,0,1,105,15,6,13,...,0,0,0,0,0,0,0,0,0,0
2,1,1,615,59,0,0,183,13,31,30,...,0,0,0,0,0,0,0,0,0,0
3,1,1,618,22,33541,0,198,9,38,25,...,0,0,0,0,0,0,0,0,0,0
4,1,1,634,30,0,0,149,7,22,20,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,5,6,6381,18,224334,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1879,5,6,6501,66,23086,1,45,7,5,7,...,0,0,0,0,0,0,0,0,0,0
1880,5,6,7064,27,217800,1,5,1,1,1,...,0,0,0,0,0,0,0,0,0,0
1881,5,6,7500,16,8886,1,18,2,4,0,...,0,0,0,0,0,0,0,0,0,0
1882,5,6,7515,64,10497,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [ ]:
# Code snippet 4
# Importing K-means clustering algorithm
from sklearn.cluster import KMeans

In [ ]:
# Code snippet 5
# Assigning the algorithm as Kmeans
kmeans = KMeans(random_state  = 42)
# Code snippet 6
# Displaying the cluster group ids using Kmeans algo
data['Cluster Group'] = kmeans.fit_predict(encoded_data)

# Displaying the original dataset with the cluster group info
data

,beds,baths,sqft,Age,lot_size,property_type,exterior_walls,roof,basement,restaurants,...,active_life,median_age,married,college_grad,property_tax,insurance,median_school,num_schools,Sales_price,Cluster Group
0,1,1,584,9,0,Apartment / Condo / Townhouse,Wood Siding,NaN,0,107,...,58,33,65,84,234,81,9.0,3,295850,6
1,1,1,612,57,0,Apartment / Condo / Townhouse,Brick,Composition Shingle,1,105,...,14,39,73,69,169,51,3.0,3,216500,0
2,1,1,615,59,0,Apartment / Condo / Townhouse,Wood Siding,NaN,0,183,...,62,28,15,86,216,74,8.0,3,279900,0
3,1,1,618,22,33541,Apartment / Condo / Townhouse,Wood Siding,NaN,0,198,...,83,36,25,91,265,92,9.0,3,379900,3
4,1,1,634,30,0,Apartment / Condo / Townhouse,Brick,NaN,0,149,...,73,37,20,75,88,30,9.0,3,340000,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1878,5,6,6381,18,224334,Single-Family,Stucco,Composition Shingle,1,0,...,1,46,76,87,1250,381,10.0,3,385000,3
1879,5,6,6501,66,23086,Single-Family,Brick,Composition Shingle,1,45,...,11,42,73,61,1553,473,9.0,3,690000,2
1880,5,6,7064,27,217800,Single-Family,Metal,Composition Shingle,1,5,...,2,43,87,66,942,287,8.0,1,600000,7
1881,5,6,7500,16,8886,Single-Family,Siding (Alum/Vinyl),Asphalt,1,18,...,6,43,61,51,803,245,5.0,2,759900,2
1882,5,6,7515,64,10497,Single-Family,Brick,Composition Shingle,1,0,...,5,37,80,86,1459,444,9.0,3,735000,2

In [ ]:
# Code snippet 7
# Exploring the dataset with the cluster group ids
data.to_csv('Zillow Dataset with Clusters info.csv')

In [ ]:
# Code snippet 8
# Displaying the cluster groups and respective data points count
data['Cluster Group'].value_counts()

Cluster Group
3    425
6    413
0    369
1    299
5    216
2    146
7     14
4      1
Name: count, dtype: int64